package qs.classhelper.service;

import java.util.List;

import qs.classhelper.entity.TbCourse;

public interface TbCourseService {
	/**
	 * 杨菲:查询所有课程及课程节点
	 */
	List<TbCourse> getAllCcd();
	/**
	 * 杨菲:删除课程体系关联课程类型,删除多个
	 */
	int delNodes(String [] s);
	/**
	 * 杨菲:删除课程类型
	 */
	int delCourse(String [] s);
	/**
     * yangfei:查询所有课程
     */
   //List<TbCourse> getAllCourse();
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int deleteByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int insert(TbCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int insertSelective(TbCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    TbCourse selectByPrimaryKey(Integer courseid);

    /**
    @author 杨菲:修改课程类型
    */
    int updateByPrimaryKeySelective(TbCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_course
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int updateByPrimaryKey(TbCourse record);
 
    
}
