package qs.classhelper.service;

import java.util.List;

import qs.classhelper.entity.TbDutiesinfo;

public interface TbDutiesinfoService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dutiesinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int deleteByPrimaryKey(Integer dutiesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dutiesinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int insert(TbDutiesinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dutiesinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int insertSelective(TbDutiesinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dutiesinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    TbDutiesinfo selectByPrimaryKey(Integer dutiesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dutiesinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int updateByPrimaryKeySelective(TbDutiesinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dutiesinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int updateByPrimaryKey(TbDutiesinfo record);
    List<TbDutiesinfo> getAllDutyName();
}
