package qs.classhelper.service;

import java.util.List;

import qs.classhelper.entity.TbMenu;

public interface TbMenuService {
	
	
	/**
	 * 查询父类菜单
	 * @return
	 */
	List<TbMenu> getAllParentMenu();
	
	
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    int deleteByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    int insert(TbMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    int insertSelective(TbMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    TbMenu selectByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    int updateByPrimaryKeySelective(TbMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    int updateByPrimaryKey(TbMenu record);
    List<TbMenu> gettbparentMenu(int dutyID);
}
