package qs.classhelper.service;

import java.util.List;

import qs.classhelper.entity.TbTeacherLessons;

public interface TbTeacherLessonsService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher_lessons
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int deleteByPrimaryKey(Integer teacherLessonsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher_lessons
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int insert(TbTeacherLessons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher_lessons
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int insertSelective(TbTeacherLessons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher_lessons
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    TbTeacherLessons selectByPrimaryKey(Integer teacherLessonsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher_lessons
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int updateByPrimaryKeySelective(TbTeacherLessons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher_lessons
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int updateByPrimaryKey(TbTeacherLessons record);
    
    List<TbTeacherLessons> select();
    List<TbTeacherLessons> showban();
    List<TbTeacherLessons> showc();
}
