package qs.classhelper.dao;

import qs.classhelper.entity.TbClassroomtype;

public interface TbClassroomtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classroomtype
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int insert(TbClassroomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classroomtype
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int insertSelective(TbClassroomtype record);
}