package qs.classhelper.dao;

import java.util.List;

import qs.classhelper.entity.TbClassnode;

public interface TbClassnodeMapper {
	/**
	 * 杨菲:删除课程节点
	 */
	int delClassnode(String [] s);
	
	
   
   
    int deleteByPrimaryKey(Integer nodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classnode
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int insert(TbClassnode record);

    /**
    @author 杨菲:添加课程节点
    */
   int insertSelective(TbClassnode record);
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classnode
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    TbClassnode selectByPrimaryKey(Integer nodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classnode
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int updateByPrimaryKeySelective(TbClassnode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_classnode
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int updateByPrimaryKey(TbClassnode record);
    /**
     * 根据班级查询课程节点
     * 
     */
    List<TbClassnode> getAllNodeByClass(String classname);
    
    /**
     * @author wangbo
     * 查询所有班级的cto课
     */
    List<TbClassnode> getAllNCtoCourse();
}