package qs.classhelper.dao;

import qs.classhelper.entity.TbExceltable;

public interface TbExceltableMapper {
  
    int deleteByPrimaryKey(Integer exceltableId);

    /**
     * 
     * @author 王博
     * 上传课表
     * 
     */
    int insert(TbExceltable record);
    TbExceltable selectByPrimaryKey(Integer exceltableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exceltable
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    int updateByPrimaryKeySelective(TbExceltable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exceltable
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TbExceltable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_exceltable
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    int updateByPrimaryKey(TbExceltable record);
}