package qs.classhelper.dao;

import java.util.List;

import qs.classhelper.entity.TbSuggestion;

public interface TbSuggestionMapper {
	
	/**
	 * 查询所有建议
	 * @return
	 */
	List<TbSuggestion> getSuggestion();
	
	/**
	 * 查询所有建议和建议的老师
	 * @return
	 */
	List<TbSuggestion> getAllSuggestion();
	
	/**
	 * 批量删除建议
	 * @param suggestionID
	 */
	public int batchDeleteSuggestions(String[] suggestionID);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_suggestion
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int deleteByPrimaryKey(Integer suggestionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_suggestion
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int insert(TbSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_suggestion
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int insertSelective(TbSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_suggestion
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    TbSuggestion selectByPrimaryKey(Integer suggestionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_suggestion
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int updateByPrimaryKeySelective(TbSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_suggestion
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    int updateByPrimaryKey(TbSuggestion record);
}