package qs.classhelper.dao;

import qs.classhelper.entity.TbTeacharinfo;

public interface TbTeacharinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacharinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int insert(TbTeacharinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacharinfo
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    int insertSelective(TbTeacharinfo record);
    
    /**
     * ¸ù¾ÝÔ±¹¤¹¤ºÅÉ¾³ý
     * @return
     */
    int delTbTeacharinfo(Integer teacherjobnumber);
    
    /**
     * ²éÑ¯µ¥¸ö¶ÔÏó
     * @param teacherID
     * @return
     */
    TbTeacharinfo getTbTeacharinfo(Integer teacherID);
    
    /**
     * ÐÞ¸Ä
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(TbTeacharinfo record);
    
}