package qs.classhelper.entity;

public class TbClassnode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classnode.nodeID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private Integer nodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classnode.nodeName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private String nodename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classnode.nodeType
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private Integer nodetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classnode.nodeID
     *
     * @return the value of tb_classnode.nodeID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public Integer getNodeid() {
        return nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classnode.nodeID
     *
     * @param nodeid the value for tb_classnode.nodeID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setNodeid(Integer nodeid) {
        this.nodeid = nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classnode.nodeName
     *
     * @return the value of tb_classnode.nodeName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classnode.nodeName
     *
     * @param nodename the value for tb_classnode.nodeName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setNodename(String nodename) {
        this.nodename = nodename == null ? null : nodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classnode.nodeType
     *
     * @return the value of tb_classnode.nodeType
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public Integer getNodetype() {
        return nodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classnode.nodeType
     *
     * @param nodetype the value for tb_classnode.nodeType
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setNodetype(Integer nodetype) {
        this.nodetype = nodetype;
    }
}