package qs.classhelper.entity;

import java.util.ArrayList;
import java.util.List;
public class TbClassroom {
    private List<TbClass> list =new ArrayList<TbClass>();
    private Integer roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classroom.roomName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private String roomname;

    public List<TbClass> getList() {
		return list;
	}

	public void setList(List<TbClass> list) {
		this.list = list;
	}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classroom.roomSize
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer roomsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classroom.roomType
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer roomtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classroom.roomID
     *
     * @return the value of tb_classroom.roomID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classroom.roomID
     *
     * @param roomid the value for tb_classroom.roomID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classroom.roomName
     *
     * @return the value of tb_classroom.roomName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classroom.roomName
     *
     * @param roomname the value for tb_classroom.roomName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classroom.roomSize
     *
     * @return the value of tb_classroom.roomSize
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getRoomsize() {
        return roomsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classroom.roomSize
     *
     * @param roomsize the value for tb_classroom.roomSize
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setRoomsize(Integer roomsize) {
        this.roomsize = roomsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classroom.roomType
     *
     * @return the value of tb_classroom.roomType
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getRoomtype() {
        return roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classroom.roomType
     *
     * @param roomtype the value for tb_classroom.roomType
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setRoomtype(Integer roomtype) {
        this.roomtype = roomtype;
    }
}