package qs.classhelper.entity;

public class TbClassroomtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classroomtype.roomType
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private Integer roomtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_classroomtype.classRoomTypeName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private String classroomtypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classroomtype.roomType
     *
     * @return the value of tb_classroomtype.roomType
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public Integer getRoomtype() {
        return roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classroomtype.roomType
     *
     * @param roomtype the value for tb_classroomtype.roomType
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setRoomtype(Integer roomtype) {
        this.roomtype = roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_classroomtype.classRoomTypeName
     *
     * @return the value of tb_classroomtype.classRoomTypeName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public String getClassroomtypename() {
        return classroomtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_classroomtype.classRoomTypeName
     *
     * @param classroomtypename the value for tb_classroomtype.classRoomTypeName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setClassroomtypename(String classroomtypename) {
        this.classroomtypename = classroomtypename == null ? null : classroomtypename.trim();
    }
}