package qs.classhelper.entity;

import java.io.Serializable;

public class TbCoursetable implements Serializable{


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.scoreNum
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private Integer scorenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_dateTime
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_classromm
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cClassromm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_morning1_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cMorning1Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_morning1_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cMorning1Teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_morning1_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cMorning1Course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_morning2_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cMorning2Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_morning2_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cMorning2Teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_morning2_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cMorning2Course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_afternoon1_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cAfternoon1Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_afternoon1_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cAfternoon1Teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_afternoon1_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cAfternoon1Course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_afternoon2_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cAfternoon2Class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_afternoon2_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cAfternoon2Teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_afternoon2_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cAfternoon2Course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_evening_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cEveningClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_evening_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cEveningTeacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_evening_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String cEveningCourse;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.scoreNum
     *
     * @return the value of tb_coursetable.scoreNum
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private int cMorning1Type ;
    private int cAfternoon1Type;
    private int cEveningType;
    public int getcMorning1Type() {
		return cMorning1Type;
	}

	public void setcMorning1Type(int cMorning1Type) {
		this.cMorning1Type = cMorning1Type;
	}

	public int getcAfternoon1Type() {
		return cAfternoon1Type;
	}

	public void setcAfternoon1Type(int cAfternoon1Type) {
		this.cAfternoon1Type = cAfternoon1Type;
	}

	public int getcEveningType() {
		return cEveningType;
	}

	public void setcEveningType(int cEveningType) {
		this.cEveningType = cEveningType;
	}

	public Integer getScorenum() {
        return scorenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.scoreNum
     *
     * @param scorenum the value for tb_coursetable.scoreNum
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setScorenum(Integer scorenum) {
        this.scorenum = scorenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_dateTime
     *
     * @return the value of tb_coursetable.c_dateTime
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcDatetime() {
        return cDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_dateTime
     *
     * @param cDatetime the value for tb_coursetable.c_dateTime
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcDatetime(String cDatetime) {
        this.cDatetime = cDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_classromm
     *
     * @return the value of tb_coursetable.c_classromm
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcClassromm() {
        return cClassromm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_classromm
     *
     * @param cClassromm the value for tb_coursetable.c_classromm
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcClassromm(String cClassromm) {
        this.cClassromm = cClassromm == null ? null : cClassromm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_morning1_class
     *
     * @return the value of tb_coursetable.c_morning1_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcMorning1Class() {
        return cMorning1Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_morning1_class
     *
     * @param cMorning1Class the value for tb_coursetable.c_morning1_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcMorning1Class(String cMorning1Class) {
        this.cMorning1Class = cMorning1Class == null ? null : cMorning1Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_morning1_teacher
     *
     * @return the value of tb_coursetable.c_morning1_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcMorning1Teacher() {
        return cMorning1Teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_morning1_teacher
     *
     * @param cMorning1Teacher the value for tb_coursetable.c_morning1_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcMorning1Teacher(String cMorning1Teacher) {
        this.cMorning1Teacher = cMorning1Teacher == null ? null : cMorning1Teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_morning1_course
     *
     * @return the value of tb_coursetable.c_morning1_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcMorning1Course() {
        return cMorning1Course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_morning1_course
     *
     * @param cMorning1Course the value for tb_coursetable.c_morning1_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcMorning1Course(String cMorning1Course) {
        this.cMorning1Course = cMorning1Course == null ? null : cMorning1Course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_morning2_class
     *
     * @return the value of tb_coursetable.c_morning2_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcMorning2Class() {
        return cMorning2Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_morning2_class
     *
     * @param cMorning2Class the value for tb_coursetable.c_morning2_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcMorning2Class(String cMorning2Class) {
        this.cMorning2Class = cMorning2Class == null ? null : cMorning2Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_morning2_teacher
     *
     * @return the value of tb_coursetable.c_morning2_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcMorning2Teacher() {
        return cMorning2Teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_morning2_teacher
     *
     * @param cMorning2Teacher the value for tb_coursetable.c_morning2_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcMorning2Teacher(String cMorning2Teacher) {
        this.cMorning2Teacher = cMorning2Teacher == null ? null : cMorning2Teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_morning2_course
     *
     * @return the value of tb_coursetable.c_morning2_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcMorning2Course() {
        return cMorning2Course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_morning2_course
     *
     * @param cMorning2Course the value for tb_coursetable.c_morning2_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcMorning2Course(String cMorning2Course) {
        this.cMorning2Course = cMorning2Course == null ? null : cMorning2Course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_afternoon1_class
     *
     * @return the value of tb_coursetable.c_afternoon1_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcAfternoon1Class() {
        return cAfternoon1Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_afternoon1_class
     *
     * @param cAfternoon1Class the value for tb_coursetable.c_afternoon1_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcAfternoon1Class(String cAfternoon1Class) {
        this.cAfternoon1Class = cAfternoon1Class == null ? null : cAfternoon1Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_afternoon1_teacher
     *
     * @return the value of tb_coursetable.c_afternoon1_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcAfternoon1Teacher() {
        return cAfternoon1Teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_afternoon1_teacher
     *
     * @param cAfternoon1Teacher the value for tb_coursetable.c_afternoon1_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcAfternoon1Teacher(String cAfternoon1Teacher) {
        this.cAfternoon1Teacher = cAfternoon1Teacher == null ? null : cAfternoon1Teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_afternoon1_course
     *
     * @return the value of tb_coursetable.c_afternoon1_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcAfternoon1Course() {
        return cAfternoon1Course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_afternoon1_course
     *
     * @param cAfternoon1Course the value for tb_coursetable.c_afternoon1_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcAfternoon1Course(String cAfternoon1Course) {
        this.cAfternoon1Course = cAfternoon1Course == null ? null : cAfternoon1Course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_afternoon2_class
     *
     * @return the value of tb_coursetable.c_afternoon2_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcAfternoon2Class() {
        return cAfternoon2Class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_afternoon2_class
     *
     * @param cAfternoon2Class the value for tb_coursetable.c_afternoon2_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcAfternoon2Class(String cAfternoon2Class) {
        this.cAfternoon2Class = cAfternoon2Class == null ? null : cAfternoon2Class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_afternoon2_teacher
     *
     * @return the value of tb_coursetable.c_afternoon2_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcAfternoon2Teacher() {
        return cAfternoon2Teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_afternoon2_teacher
     *
     * @param cAfternoon2Teacher the value for tb_coursetable.c_afternoon2_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcAfternoon2Teacher(String cAfternoon2Teacher) {
        this.cAfternoon2Teacher = cAfternoon2Teacher == null ? null : cAfternoon2Teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_afternoon2_course
     *
     * @return the value of tb_coursetable.c_afternoon2_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcAfternoon2Course() {
        return cAfternoon2Course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_afternoon2_course
     *
     * @param cAfternoon2Course the value for tb_coursetable.c_afternoon2_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcAfternoon2Course(String cAfternoon2Course) {
        this.cAfternoon2Course = cAfternoon2Course == null ? null : cAfternoon2Course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_evening_class
     *
     * @return the value of tb_coursetable.c_evening_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcEveningClass() {
        return cEveningClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_evening_class
     *
     * @param cEveningClass the value for tb_coursetable.c_evening_class
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcEveningClass(String cEveningClass) {
        this.cEveningClass = cEveningClass == null ? null : cEveningClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_evening_teacher
     *
     * @return the value of tb_coursetable.c_evening_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcEveningTeacher() {
        return cEveningTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_evening_teacher
     *
     * @param cEveningTeacher the value for tb_coursetable.c_evening_teacher
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcEveningTeacher(String cEveningTeacher) {
        this.cEveningTeacher = cEveningTeacher == null ? null : cEveningTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coursetable.c_evening_course
     *
     * @return the value of tb_coursetable.c_evening_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public String getcEveningCourse() {
        return cEveningCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coursetable.c_evening_course
     *
     * @param cEveningCourse the value for tb_coursetable.c_evening_course
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    public void setcEveningCourse(String cEveningCourse) {
        this.cEveningCourse = cEveningCourse == null ? null : cEveningCourse.trim();
    }
}