package qs.classhelper.entity;

import java.util.Date;

public class TbCoursetableMy {


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.scoreNum
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private Integer scorenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coursetable.c_dateTime
     *
     * @mbg.generated Tue Jan 23 19:33:11 CST 2018
     */
    private String date1;
	private Date cDatetime;
    private String cMorning1Class;
    private String cClassromm1;
    private String cClassromm2;
    private String cClassromm3;
    private String cMorning1Course;
    private String cMorning2Class;
    private String cMorning2Course;
    private String cAfternoon1Class;
    private String cAfternoon1Teacher;
    private String cAfternoon1Course;
    private String cAfternoon2Class;
    private String cAfternoon2Teacher;
    private String cAfternoon2Course;
    private String cEveningClass;
    private String cEveningTeacher;
    private String cEveningCourse;
    private int cMorning1Type ;
    private int cAfternoon1Type;
    private int cEveningType;
    
	public int getcMorning1Type() {
		return cMorning1Type;
	}
	public void setcMorning1Type(int cMorning1Type) {
		this.cMorning1Type = cMorning1Type;
	}
	public int getcAfternoon1Type() {
		return cAfternoon1Type;
	}
	public void setcAfternoon1Type(int cAfternoon1Type) {
		this.cAfternoon1Type = cAfternoon1Type;
	}
	public int getcEveningType() {
		return cEveningType;
	}
	public void setcEveningType(int cEveningType) {
		this.cEveningType = cEveningType;
	}
	public Integer getScorenum() {
		return scorenum;
	}
	public void setScorenum(Integer scorenum) {
		this.scorenum = scorenum;
	}
	public Date getcDatetime() {
		return cDatetime;
	}
	public void setcDatetime(Date cDatetime) {
		this.cDatetime = cDatetime;
	}
	public String getcMorning1Class() {
		return cMorning1Class;
	}
	public void setcMorning1Class(String cMorning1Class) {
		this.cMorning1Class = cMorning1Class;
	}
	public String getcClassromm1() {
		return cClassromm1;
	}
	public void setcClassromm1(String cClassromm1) {
		this.cClassromm1 = cClassromm1;
	}
	public String getcClassromm2() {
		return cClassromm2;
	}
	public void setcClassromm2(String cClassromm2) {
		this.cClassromm2 = cClassromm2;
	}
	public String getcClassromm3() {
		return cClassromm3;
	}
	public void setcClassromm3(String cClassromm3) {
		this.cClassromm3 = cClassromm3;
	}
	public String getcMorning1Course() {
		return cMorning1Course;
	}
	public void setcMorning1Course(String cMorning1Course) {
		this.cMorning1Course = cMorning1Course;
	}
	public String getcMorning2Class() {
		return cMorning2Class;
	}
	public void setcMorning2Class(String cMorning2Class) {
		this.cMorning2Class = cMorning2Class;
	}
	public String getcMorning2Course() {
		return cMorning2Course;
	}
	public void setcMorning2Course(String cMorning2Course) {
		this.cMorning2Course = cMorning2Course;
	}
	public String getcAfternoon1Class() {
		return cAfternoon1Class;
	}
	public void setcAfternoon1Class(String cAfternoon1Class) {
		this.cAfternoon1Class = cAfternoon1Class;
	}
	public String getcAfternoon1Teacher() {
		return cAfternoon1Teacher;
	}
	public void setcAfternoon1Teacher(String cAfternoon1Teacher) {
		this.cAfternoon1Teacher = cAfternoon1Teacher;
	}
	public String getcAfternoon1Course() {
		return cAfternoon1Course;
	}
	public void setcAfternoon1Course(String cAfternoon1Course) {
		this.cAfternoon1Course = cAfternoon1Course;
	}
	public String getcAfternoon2Class() {
		return cAfternoon2Class;
	}
	public void setcAfternoon2Class(String cAfternoon2Class) {
		this.cAfternoon2Class = cAfternoon2Class;
	}
	public String getcAfternoon2Teacher() {
		return cAfternoon2Teacher;
	}
	public void setcAfternoon2Teacher(String cAfternoon2Teacher) {
		this.cAfternoon2Teacher = cAfternoon2Teacher;
	}
	public String getcAfternoon2Course() {
		return cAfternoon2Course;
	}
	public void setcAfternoon2Course(String cAfternoon2Course) {
		this.cAfternoon2Course = cAfternoon2Course;
	}
	public String getcEveningClass() {
		return cEveningClass;
	}
	public void setcEveningClass(String cEveningClass) {
		this.cEveningClass = cEveningClass;
	}
	public String getcEveningTeacher() {
		return cEveningTeacher;
	}
	public void setcEveningTeacher(String cEveningTeacher) {
		this.cEveningTeacher = cEveningTeacher;
	}
	public String getcEveningCourse() {
		return cEveningCourse;
	}
	public void setcEveningCourse(String cEveningCourse) {
		this.cEveningCourse = cEveningCourse;
	}
    public String getDate1() {
		return date1;
	}
	public void setDate1(String date1) {
		this.date1 = date1;
	}
}