package qs.classhelper.entity;

import java.util.List;

public class TbCourse {
	/**
	 * @杨菲:创建课程节点属性
	 */
	List<TbClassnode> classnodes;
	public List<TbClassnode> getClassnodes() {
		return classnodes;
	}

	public void setClassnodes(List<TbClassnode> classnodes) {
		this.classnodes = classnodes;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.courseID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.courseName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.coursePeriod
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer courseperiod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.courseID
     *
     * @return the value of tb_course.courseID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.courseID
     *
     * @param courseid the value for tb_course.courseID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.courseName
     *
     * @return the value of tb_course.courseName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.courseName
     *
     * @param coursename the value for tb_course.courseName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.coursePeriod
     *
     * @return the value of tb_course.coursePeriod
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getCourseperiod() {
        return courseperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.coursePeriod
     *
     * @param courseperiod the value for tb_course.coursePeriod
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setCourseperiod(Integer courseperiod) {
        this.courseperiod = courseperiod;
    }
}