package qs.classhelper.entity;

public class TbDutiesinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dutiesinfo.dutiesID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private Integer dutiesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dutiesinfo.dutiesName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private String dutiesname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dutiesinfo.dutiesID
     *
     * @return the value of tb_dutiesinfo.dutiesID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public Integer getDutiesid() {
        return dutiesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dutiesinfo.dutiesID
     *
     * @param dutiesid the value for tb_dutiesinfo.dutiesID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setDutiesid(Integer dutiesid) {
        this.dutiesid = dutiesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dutiesinfo.dutiesName
     *
     * @return the value of tb_dutiesinfo.dutiesName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public String getDutiesname() {
        return dutiesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dutiesinfo.dutiesName
     *
     * @param dutiesname the value for tb_dutiesinfo.dutiesName
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setDutiesname(String dutiesname) {
        this.dutiesname = dutiesname == null ? null : dutiesname.trim();
    }
}