package qs.classhelper.entity;

public class TbDutyMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_duty_menu.duty_menuID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private Integer dutyMenuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_duty_menu.dutyID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private Integer dutyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_duty_menu.menuID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    private Long menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_duty_menu.duty_menuID
     *
     * @return the value of tb_duty_menu.duty_menuID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public Integer getDutyMenuid() {
        return dutyMenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_duty_menu.duty_menuID
     *
     * @param dutyMenuid the value for tb_duty_menu.duty_menuID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setDutyMenuid(Integer dutyMenuid) {
        this.dutyMenuid = dutyMenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_duty_menu.dutyID
     *
     * @return the value of tb_duty_menu.dutyID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public Integer getDutyid() {
        return dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_duty_menu.dutyID
     *
     * @param dutyid the value for tb_duty_menu.dutyID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setDutyid(Integer dutyid) {
        this.dutyid = dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_duty_menu.menuID
     *
     * @return the value of tb_duty_menu.menuID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_duty_menu.menuID
     *
     * @param menuid the value for tb_duty_menu.menuID
     *
     * @mbg.generated Fri Jan 19 17:30:12 CST 2018
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }
}