package qs.classhelper.entity;

public class TbExceltable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_exceltable.exceltable_id
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    private Integer exceltableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_exceltable.exceltable_name
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    private String exceltableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_exceltable.exceltable_filepath
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    private String exceltableFilepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_exceltable.exceltable_type
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    private String exceltableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_exceltable.exceltable_file
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    private byte[] exceltableFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_exceltable.exceltable_id
     *
     * @return the value of tb_exceltable.exceltable_id
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public Integer getExceltableId() {
        return exceltableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_exceltable.exceltable_id
     *
     * @param exceltableId the value for tb_exceltable.exceltable_id
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public void setExceltableId(Integer exceltableId) {
        this.exceltableId = exceltableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_exceltable.exceltable_name
     *
     * @return the value of tb_exceltable.exceltable_name
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public String getExceltableName() {
        return exceltableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_exceltable.exceltable_name
     *
     * @param exceltableName the value for tb_exceltable.exceltable_name
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public void setExceltableName(String exceltableName) {
        this.exceltableName = exceltableName == null ? null : exceltableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_exceltable.exceltable_filepath
     *
     * @return the value of tb_exceltable.exceltable_filepath
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public String getExceltableFilepath() {
        return exceltableFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_exceltable.exceltable_filepath
     *
     * @param exceltableFilepath the value for tb_exceltable.exceltable_filepath
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public void setExceltableFilepath(String exceltableFilepath) {
        this.exceltableFilepath = exceltableFilepath == null ? null : exceltableFilepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_exceltable.exceltable_type
     *
     * @return the value of tb_exceltable.exceltable_type
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public String getExceltableType() {
        return exceltableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_exceltable.exceltable_type
     *
     * @param exceltableType the value for tb_exceltable.exceltable_type
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public void setExceltableType(String exceltableType) {
        this.exceltableType = exceltableType == null ? null : exceltableType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_exceltable.exceltable_file
     *
     * @return the value of tb_exceltable.exceltable_file
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public byte[] getExceltableFile() {
        return exceltableFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_exceltable.exceltable_file
     *
     * @param exceltableFile the value for tb_exceltable.exceltable_file
     *
     * @mbggenerated Sat Jan 27 10:36:14 CST 2018
     */
    public void setExceltableFile(byte[] exceltableFile) {
        this.exceltableFile = exceltableFile;
    }
}