package qs.classhelper.entity;

import java.util.ArrayList;
import java.util.List;

public class TbMenu {
	
	
	//添加小类
	private List<TbMenu> childsMenu=new ArrayList<TbMenu>();
	
    public List<TbMenu> getChildsMenu() {
		return childsMenu;
	}

	public void setChildsMenu(List<TbMenu> childsMenu) {
		this.childsMenu = childsMenu;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menuID
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menuName
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menuParentId
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    private Integer menuparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menuUrl
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    private String menuurl;
    
    
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menuID
     *
     * @return the value of tb_menu.menuID
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menuID
     *
     * @param menuid the value for tb_menu.menuID
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menuName
     *
     * @return the value of tb_menu.menuName
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menuName
     *
     * @param menuname the value for tb_menu.menuName
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menuParentId
     *
     * @return the value of tb_menu.menuParentId
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public Integer getMenuparentid() {
        return menuparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menuParentId
     *
     * @param menuparentid the value for tb_menu.menuParentId
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public void setMenuparentid(Integer menuparentid) {
        this.menuparentid = menuparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menuUrl
     *
     * @return the value of tb_menu.menuUrl
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menuUrl
     *
     * @param menuurl the value for tb_menu.menuUrl
     *
     * @mbggenerated Fri Jan 19 16:49:04 CST 2018
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }
}