package qs.classhelper.entity;

import java.util.Date;

public class TbSuggestion {
	
	private TbTeacher tbTeacher = new TbTeacher();
    public TbSuggestion() {
		super();
	}

	public TbSuggestion(TbTeacher tbTeacher) {
		super();
		this.tbTeacher = tbTeacher;
	}

	public TbTeacher getTbTeacher() {
		return tbTeacher;
	}

	public void setTbTeacher(TbTeacher tbTeacher) {
		this.tbTeacher = tbTeacher;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_suggestion.suggestionID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer suggestionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_suggestion.suggestionTitle
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private String suggestiontitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_suggestion.suggestionContent
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private String suggestioncontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_suggestion.releaseTime
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Date releasetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_suggestion.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer teacherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_suggestion.suggestionID
     *
     * @return the value of tb_suggestion.suggestionID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getSuggestionid() {
        return suggestionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_suggestion.suggestionID
     *
     * @param suggestionid the value for tb_suggestion.suggestionID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setSuggestionid(Integer suggestionid) {
        this.suggestionid = suggestionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_suggestion.suggestionTitle
     *
     * @return the value of tb_suggestion.suggestionTitle
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public String getSuggestiontitle() {
        return suggestiontitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_suggestion.suggestionTitle
     *
     * @param suggestiontitle the value for tb_suggestion.suggestionTitle
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setSuggestiontitle(String suggestiontitle) {
        this.suggestiontitle = suggestiontitle == null ? null : suggestiontitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_suggestion.suggestionContent
     *
     * @return the value of tb_suggestion.suggestionContent
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public String getSuggestioncontent() {
        return suggestioncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_suggestion.suggestionContent
     *
     * @param suggestioncontent the value for tb_suggestion.suggestionContent
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setSuggestioncontent(String suggestioncontent) {
        this.suggestioncontent = suggestioncontent == null ? null : suggestioncontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_suggestion.releaseTime
     *
     * @return the value of tb_suggestion.releaseTime
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_suggestion.releaseTime
     *
     * @param releasetime the value for tb_suggestion.releaseTime
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_suggestion.teacherID
     *
     * @return the value of tb_suggestion.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_suggestion.teacherID
     *
     * @param teacherid the value for tb_suggestion.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }
}