package qs.classhelper.entity;

import java.util.ArrayList;
import java.util.List;

public class TbTeacherLessons {
	//属性名
	private TbClass tbClass;
	private  TbTeacher tbTeacher;
	
	
    public TbClass getTbClass() {
		return tbClass;
	}

	public void setTbClass(TbClass tbClass) {
		this.tbClass = tbClass;
	}

	public TbTeacher getTbTeacher() {
		return tbTeacher;
	}

	public void setTbTeacher(TbTeacher tbTeacher) {
		this.tbTeacher = tbTeacher;
	}
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher_lessons.teacher_lessons_ID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer teacherLessonsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher_lessons.classID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher_lessons.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer teacherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher_lessons.teacher_lessons_ID
     *
     * @return the value of tb_teacher_lessons.teacher_lessons_ID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getTeacherLessonsId() {
        return teacherLessonsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher_lessons.teacher_lessons_ID
     *
     * @param teacherLessonsId the value for tb_teacher_lessons.teacher_lessons_ID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherLessonsId(Integer teacherLessonsId) {
        this.teacherLessonsId = teacherLessonsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher_lessons.classID
     *
     * @return the value of tb_teacher_lessons.classID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher_lessons.classID
     *
     * @param classid the value for tb_teacher_lessons.classID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher_lessons.teacherID
     *
     * @return the value of tb_teacher_lessons.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher_lessons.teacherID
     *
     * @param teacherid the value for tb_teacher_lessons.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }
    List<TbTeacher>tbteacher=new ArrayList<TbTeacher>();
    List<TbClass>tbclass=new ArrayList<TbClass>();

	public List<TbTeacher> getTbteacher() {
		return tbteacher;
	}

	public void setTbteacher(List<TbTeacher> tbteacher) {
		this.tbteacher = tbteacher;
	}

	public List<TbClass> getTbclass() {
		return tbclass;
	}

	public void setTbclass(List<TbClass> tbclass) {
		this.tbclass = tbclass;
	}
}