package qs.classhelper.entity;

import java.util.Date;

public class TbTeacher {
    public TbTeacher() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacherJobNumber
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer teacherjobnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacherName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private String teachername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacherPwd
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private String teacherpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacherInTime
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Date teacherintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.dutiesID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer dutiesid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacherState
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    private Integer teacherstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacherID
     *
     * @return the value of tb_teacher.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacherID
     *
     * @param teacherid the value for tb_teacher.teacherID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacherJobNumber
     *
     * @return the value of tb_teacher.teacherJobNumber
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getTeacherjobnumber() {
        return teacherjobnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacherJobNumber
     *
     * @param teacherjobnumber the value for tb_teacher.teacherJobNumber
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherjobnumber(Integer teacherjobnumber) {
        this.teacherjobnumber = teacherjobnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacherName
     *
     * @return the value of tb_teacher.teacherName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacherName
     *
     * @param teachername the value for tb_teacher.teacherName
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername == null ? null : teachername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacherPwd
     *
     * @return the value of tb_teacher.teacherPwd
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public String getTeacherpwd() {
        return teacherpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacherPwd
     *
     * @param teacherpwd the value for tb_teacher.teacherPwd
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherpwd(String teacherpwd) {
        this.teacherpwd = teacherpwd == null ? null : teacherpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacherInTime
     *
     * @return the value of tb_teacher.teacherInTime
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Date getTeacherintime() {
        return teacherintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacherInTime
     *
     * @param teacherintime the value for tb_teacher.teacherInTime
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherintime(Date teacherintime) {
        this.teacherintime = teacherintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.dutiesID
     *
     * @return the value of tb_teacher.dutiesID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getDutiesid() {
        return dutiesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.dutiesID
     *
     * @param dutiesid the value for tb_teacher.dutiesID
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setDutiesid(Integer dutiesid) {
        this.dutiesid = dutiesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacherState
     *
     * @return the value of tb_teacher.teacherState
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public Integer getTeacherstate() {
        return teacherstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacherState
     *
     * @param teacherstate the value for tb_teacher.teacherState
     *
     * @mbg.generated Fri Jan 19 00:18:10 CST 2018
     */
    public void setTeacherstate(Integer teacherstate) {
        this.teacherstate = teacherstate;
    }
}